config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :image_posts
  resources :text_posts
  resources :posts
  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  # Area de validaciones
  validates :body, presence: true

end

app/models/image_post.rb
class ImagePost < Post

  # Area de validaciones
  validates :url, presence: true # Para un Post de tipo imagen, obligatoriamente, tiene que tener una url

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  # Area de validaciones
  validates :user_id, presence: true # Obligatoriamente, tiene que pertenecer a un User
  validates :type, presence: :true   # Obligatoriamente, tiene que tener un tipo de Post

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :leader, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/text_post.rb
class TextPost < Post

  # Area de validaciones
  validates :body, presence: true # Para un Post de tipo texto, obligatoriamente, tiene que tener un cuerpo de texto (body)

end

app/models/user.rb
class User < ActiveRecord::Base

  # Hacemos uso de Bcrypt para almacenar nuestro password de forma segura
  # Al hacer uso de esto, la gema espera que exista un campo llamado 'password_digest'
  has_secure_password

  # Relaciones para suscripciones (Sacar que usuarios sigue un usuario)
  has_many :subscriptions, foreign_key: :follower_id, dependent: :destroy
  has_many :leaders, through: :subscriptions

  # Relaciones reversas para suscripciones (Sacar seguidores de un usuario)
  has_many :reverse_subscriptions, class_name: 'Subscription', foreign_key: :leader_id, dependent: :destroy
  has_many :followers, through: :reverse_subscriptions

  # Relaciones para con los Posts y sus derivaciones
  has_many :posts, dependent: :destroy # Tengo muchos post, si elimino el user, elimino los posts asociados
  has_many :text_posts, dependent: :destroy # Tengo text_posts post, si elimino el user, elimino los text_posts asociados
  has_many :image_posts, dependent: :destroy # Tengo muchos image_posts, si elimino el user, elimino los image_posts asociados

  # Relacion con los comentarios
  has_many :comments

  # Area de validaciones

  # Verifico que exista un correo electronico y ademas, que este sea unico en mi tabla Users
  validates :email, presence: true, uniqueness: true

  # Area de metodos

  # Metodo para saber si un usuario sigue a otro
  def following?(leader)
    leaders.include? leader
  end

  # Metodo para seguir a un usuario
  def follow!(leader)
    if leader != self and !following?(leader)
      leaders << leader
    end
  end

  def timeline_user_ids
    leader_ids + [id]
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  # Metodo para obtener el usuario actualmente logueado
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  # Dejo el metodo 'current_user' al alcance de toda la aplicacion
  helper_method :current_user

  # Metodo bang para revisar que exista un usuario logeado,
  # si existe, no hace nada, de lo contrario redirecciona a la uri del login
  def authenticate_user!
    redirect_to login_path if !current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/image_posts_controller.rb
class ImagePostsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Metodo callback para requerir un usuario logueado
  # se ejecuatara antes de cada ves que se consuma un recurso
  before_action :authenticate_user!

  def index
    user_ids = current_user.timeline_user_ids
    # @posts = Post.all
    @posts = Post.where(user_id: user_ids).order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # Solo se dedica a renderizar vista
  end

  def create
    user = User.find_by(email: params[:email]) # Busco el usuario por el email
    if user and user.authenticate(params[:password]) # Si el usuario existe(fue encontrado), y el password es correcto, entonces:
      session[:user_id] = user.id # Guardo en las sesiones del servidor, el id del usuario para posteriores operaciones
      redirect_to root_url, notice: "Ha iniciado sesion satisfactoriamente!" # Redireccione a la ruta raiz y muestre un mensaje
    else
      flash.now.alert = "email o contraseña invalidos" # Muestre un mensaje de error
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Sesion terminada satisfactoriamente!"
  end
end

app/controllers/text_posts_controller.rb
class TextPostsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to root_url, notice: "Bienvenido a Diplo social "
    else
      render "new"
    end
  end

  private

  # Metodo para filtrar los parametros que lleguen del formulario, la internet es peligrosa!
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/image_posts_helper.rb
module ImagePostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/text_posts_helper.rb
module TextPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/image_posts/_image_post.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= image_post.title %>
    </h3>
  </div>

  <div class="panel-body">
    <p><em><%= image_post.user.name %></em></p>
    <%= image_tag image_post.url, class: "img-responsive" %>
    <%= image_post.body %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiploSocial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

  <!--Sesion de hash noticias-->
  <% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
  <% end %>

  <% if alert %>
      <div class="alert alert-danger">
        <%= alert %>
      </div>
  <% end %>

  <!--sesion de barra de usuario-->
  <div class="pull-right">
    <% if current_user %>
        <%= link_to 'Log Out', logout_path %>
    <% else %>
        <%= link_to 'Log In', login_path %> |
        <%= link_to 'Registrarse', signup_path %>
    <% end %>
  </div>
  <%= yield %>
</div>
</body>
</html>

app/views/posts/index.html.erb
<div class="page-header">
  <h1>Home</h1>
</div>

<%= render @posts %>

app/views/posts/show.html.erb
<div class="page-header">
  <h1>Post</h1>
</div>

<%= render @post%>
<%= link_to "Home", post_path, class: "btn btn-default" %>

app/views/text_posts/_text_post.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= text_post.title %>
    </h3>
  </div>

  <div class="panel-body">
    <p><em><%= text_post.user.name %></em></p>
    <%= text_post.body %>
  </div>
</div>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Registro</h1>
</div>

<%= form_for(@user) do |f| %>

    <!--En caso de tener errores de retorno, se mestran-->
    <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <strong>
            <%= pluralize(@user.errors.count, "error") %>
            Tenga en cuenta lo siguiente:
          </strong>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <!--Parte del formulario-->
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>